# Generated by Django 6.0.3 on 2026-04-02 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])])),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='annotator_i_uploade_a29ded_idx'), models.Index(fields=['name'], name='annotator_i_name_332d4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('x', models.IntegerField(help_text='X coordinate of top-left corner')),
                ('y', models.IntegerField(help_text='Y coordinate of top-left corner')),
                ('width', models.IntegerField(help_text='Width of bounding box')),
                ('height', models.IntegerField(help_text='Height of bounding box')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.image')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['image', 'created_at'], name='annotator_a_image_i_bd4dc9_idx')],
            },
        ),
    ]
