# Generated by Django 6.0.3 on 2026-04-03 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='class_id',
            field=models.IntegerField(default=0, help_text='Class ID for YOLO format (0-indexed)'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x_center',
            field=models.FloatField(default=0.5, help_text='Normalized center X coordinate (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y_center',
            field=models.FloatField(default=0.5, help_text='Normalized center Y coordinate (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='height',
            field=models.FloatField(default=0.5, help_text='Normalized height (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='width',
            field=models.FloatField(default=0.5, help_text='Normalized width (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='x',
            field=models.IntegerField(default=0, help_text='X coordinate of top-left corner (legacy)'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='y',
            field=models.IntegerField(default=0, help_text='Y coordinate of top-left corner (legacy)'),
        ),
    ]
